spring:
  application:
    name: ecommerce-api-mivas

  data:
    mongodb:
      host: localhost
      port: 27017
      database: emivasdb
    redis:
      host: localhost
      port: 6379
      password: sa

  cache:
    redis:
      time-to-live: 60000

emivas:
  client:
    platzi: https://api.escuelajs.co/api/v1